package com.tvh.warehouseManager.domein;

import com.fasterxml.jackson.annotation.JsonBackReference;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * This is the product class. Every product will be linked to a warehouse.
 * 
 * @author simon
 */
@Entity
@Table
public class Product {
    /**
    * The ID of the product
    * This attribute will be generated by the database if the product is new.
    */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;
    
    /**
    * The name of the product
    */
    private String name;
    
    /**
    * The reference to the warehouse where the product is
    * This attribute will have the warehouseID in the database
    * This attribute can't be null
    */
    @ManyToOne
    @JoinColumn(name = "warehouse_id", nullable = false)
    @JsonBackReference
    private Warehouse warehouse;

    /**
    * <p>This constructor will be used to get data from the database</p>
    * @since 1.0
    */
    public Product() {}
    
    /**
    * <p>This constructor will be used to make new products</p>
    * @param id the productID
    * @param name the name of the product
    * @param warehouse the warehouse where the product is stored
    * @since 1.0
    */
    public Product(int id, String name, Warehouse warehouse) {
        this.id = id;
        this.name = name;
        this.warehouse = warehouse;
    }

    /**
    * <p>This method will return the warehouse</p>
    * @return the warehouse
    * @since 1.0
    */
    public Warehouse getWarehouse() {
        return warehouse;
    }

    /**
    * <p>This method will save a new warehouse when the product is transfered</p>
    * @param warehouse the new warehouse
    * @since 1.0
    */
    public void setWarehouse(Warehouse warehouse) {
        this.warehouse = warehouse;
    }
    
    /**
    * <p>This method will return the id of the product</p>
    * @return the id
    * @since 1.0
    */
    public int getId() {
        return id;
    }

    /**
    * <p>This method will set the ID of the product</p>
    * @param id the new productID
    * @since 1.0
    */
    public void setId(int id) {
        this.id = id;
    }

    /**
    * <p>This method will return the name of the product</p>
    * @return the name
    * @since 1.0
    */
    public String getName() {
        return name;
    }

    /**
    * <p>This method will set a new name for the product</p>
    * @param name the new name of the product
    * @since 1.0
    */
    public void setName(String name) {
        if(name != null && name.trim().length() > 3) {
            this.name = name;
        }
    }
}
