package com.tvh.warehouseManager.domein;

import com.tvh.warehouseManager.exception.NoCapacityLeftException;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * This is the warehouse class. This class is the center of the project.
 * Warehouses can contain products.
 *
 * @author simon
 */
@Entity
@Table(name = "warehouses")
public class Warehouse {
    /**
    * The ID of the warehouse
    * This attribute will be generated by the database if the warehouse is new.
    */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    /**
    * The name of the warehouse
    */
    private String name;
    
    /**
    * The maximum number of products that the warehouse can contain
    */
    private int maximumCapacity;
    
    /**
    * The number of products that the warehouse has.
    */
    private int capacityUsed;
    
    /**
    * The list of products that the warehouse contains
    * Warehouse has the responsibility for mapping the products
    */
    @OneToMany(mappedBy = "warehouse")
    private List<Product> products;
    
    public Warehouse() {}

    public Warehouse(int maximumCapacity, String name) {
        this.maximumCapacity = maximumCapacity;
        this.capacityUsed = 0;
        this.products = new ArrayList<>();
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        if(name != null && name.trim().length() > 3) {
            this.name = name;
        }
    }

    public int getCapacityUsed() {
        return capacityUsed;
    }

    public int getMaximumCapacity() {
        return maximumCapacity;
    }
    
    public void setMaximumCapacity(int maximumCapacity) {
        if(maximumCapacity > this.capacityUsed) {
            this.maximumCapacity = maximumCapacity;
        } else {
            throw new NoCapacityLeftException("There is no free space in warehouse " + this.getName() + ", so you can't delete capacity");
        }
    }

    public List<Product> getProducts() {
        return products;
    }
    
    public int calculateCapacityLeft() {
        return this.maximumCapacity - this.capacityUsed;
    }
    
    public void addProduct(Product p) {
        if(this.maximumCapacity > this.capacityUsed) {
            this.products.add(p);
            this.capacityUsed++;
        } else {
            throw new NoCapacityLeftException("There is no free space in warehouse (" + this.getId() + ") " + this.getName());
        }
    }
    
    public Product deleteProduct(int id) {
        Product product = this.products.stream().filter(p -> p.getId() == id).findFirst().get();
        this.products.remove(product);
        this.capacityUsed--;
        return product;
    }

    public void removeProduct(Product product) {
        this.products.remove(product);
    }
}
